"http://{all}/":
    type: redirect
    # Redirect from HTTP to HTTPS
    to: "https://{all}/"

"https://{all}/":
    type: upstream
    upstream: "afsy:http"

"https://www.{all}/":
    type: redirect
    to: "https://{all}/"

"http://www.{all}/":
    type: redirect
    to: "https://{all}/"
